logdir: null
device: cpu

total_steps: 2000
train_every: 5

environment:
  name: CartPole-v1
  image_width: 256
  image_height: 256
  seed: 0

replay_buffer:
  capacity: 1000
  batch_size: 8


agent:
  learning_rate: 0.001

  world_model:
    embedded_observation_size: 256
    deterministic_state_size: 64
    stochastic_state_size: 64

    encoder:
      depth: 32
      kernel_size: 4
      stride: 2
    
    decoder:
      depth: 32
      kernel_size: 5
      stride: 2

    representation_model:
      hidden_size: 64
    
    transition_model:
      hidden_size: 64

    recurrent_model:
      hidden_size: 64

    reward_model:
      hidden_size: 64
    
    cost_model:
      hidden_size: 64
      
  


