logdir: null
device: cuda

total_steps: 100000
train_every: 5

environment:
  name: MountainCar-v0
  image_width: 64
  image_height: 64
  seed: 0
  action_repeat: 10

replay_buffer:
  capacity: 5000
  batch_size: 16
  chunk_length: 64


agent:
  world_model:
    embedded_observation_size: 256
    deterministic_state_size: 64
    stochastic_state_size: 64

    learning_rate: 0.0003
    clip_grad: 1.0

    encoder:
      depth: 32
      kernel_size: 4
      stride: 2
    
    decoder:
      depth: 32
      kernel_size: 5
      stride: 2

    representation_model:
      hidden_size: 64
    
    transition_model:
      hidden_size: 64

    recurrent_model:
      hidden_size: 64

    reward_model:
      hidden_size: 64
    
    cost_model:
      hidden_size: 64
      
  


